### ISSUE TITLE
Dynamic Multi-scale Filters for Semantic Segmentation

### ISSUE THREAD

**Issue by lartpang** [lartpang/PyTorchCoding#1]
![image](https://user-images.githubusercontent.com/26847524/74925080-8ec87a80-540e-11ea-9dd4-8209b3dd33bd.png)

![image](https://user-images.githubusercontent.com/26847524/74925122-a0aa1d80-540e-11ea-96d5-74e39fb2aa1a.png)

**Comment by morning4346** [comment]
你好，当我使用您的模块加入到我自己的网络中时，会出现错误，RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)，您知道是什么原因吗？
